[build]
  publish = "."

[dev]
  publish = "."
  port = 8888

# Optional: redirect all routes to index.html if we add more pages in future
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect pretty affiliate paths like /go/lars-drumsticks -> /go/index.html?slug=lars-drumsticks
[[redirects]]
  from = "/go/*"
  to = "/go/index.html?slug=:splat"
  status = 200
